name: Release

on:
  push:
    branches:
      - linux-support

jobs:
  prepare:
    name: Create draft release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Yes, this is the lazy way of doing it. Am I lazy? Yes.
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### [Install guide](https://github.com/ethangreen-dev/lovely-injector?tab=readme-ov-file#manual-installation)" >> NOTE.md
          echo "|OS|Download|" >> NOTE.md
          echo "|--|--|" >> NOTE.md
          echo "|Windows|[lovely-x86_64-pc-windows-msvc.zip](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-x86_64-pc-windows-msvc.zip)|" >> NOTE.md
          echo "|Mac (Arm)|[lovely-aarch64-apple-darwin.tar.gz](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-aarch64-apple-darwin.tar.gz)|" >> NOTE.md
          echo "|Mac (x86)|[lovely-x86_64-apple-darwin.tar.gz](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-x86_64-apple-darwin.tar.gz)|" >> NOTE.md

          gh release create ${{ github.ref_name }} \
          --title "${{ github.ref_name }}" \
          --draft  \
          --generate-notes \
          --notes-file NOTE.md \

  build-linux:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}

      - name: add target
        run: |
          rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --target ${{ matrix.target }} --package lovely-unix --release

      - name: Compress
        run: |
          cd ./target/${{ matrix.target }}/
          7z a "lovely-${{ matrix.target }}.zip" release
          mv "lovely-${{ matrix.target }}.zip" ${{ github.workspace }}

      - name: Submit build artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload ${{ github.ref_name }} lovely-${{ matrix.target }}.zip
